---
title: "TestLogistic"
author: "Lin Keke"
date: "1/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
```


```{r}
library(LogisticRegression)
data("breast-cancer-wisconsin")
head(datas,20)
```
```{r}
X_data <- datas[2:10]
Y_data <- datas[11]
X_norm <- scale(X_data)
dim(X_norm)
dim(Y_data)
#为X添加偏置项
X <- cbind(X_norm, 1)
y <- Y_data
#为Y转化为[0,1]
y[[1]][which(y == 2)] <- 1
y[[1]][which(y != 1)] <- 0

library(TestLIn)
set.seed(1)
beta_grad <- as.matrix(rnorm(dim(X)[2])) * 0.01
beta_grad1 <- GradientDescent(beta_grad, X, y)$beta
iteration.No1.1 <- GradientDescent(beta_grad, X, y)$iList
costList1.1 <- GradientDescent(beta_grad, X, y)$costList
print(beta_grad1[,1])
print(plotAUC(beta_grad1, X, y))

beta_grad2 <- GradientDescent(beta_grad, X, y, regulation = 2)$beta
iteration.No1.2 <- GradientDescent(beta_grad, X, y, regulation = 2)$iList
costList1.2 <- GradientDescent(beta_grad, X, y, regulation = 2)$costList
print(beta_grad2[,1])
print(plotAUC(beta_grad2, X, y))



```
```{r}
set.seed(1)
beta_nt <- as.matrix(rnorm(dim(X)[2])) * 0.01
beta_nt1 <- Newton(beta_nt, X, y)$beta
iteration.No2.1 <- Newton(beta_nt, X, y)$iList
costList2.1 <- Newton(beta_nt, X, y)$costList
print(beta_nt1[,1])
print(precision_score(beta_nt1[,1], X, y))

beta_nt2 <- Newton(beta_nt, X, y, regulation = 2)$beta
iteration.No2.2 <- Newton(beta_nt, X, y, regulation = 2)$iList
costList2.2 <- Newton(beta_nt, X, y, regulation = 2)$costList
print(beta_nt2[,1])
print(precision_score(beta_nt2[,1], X, y))
```
```{r}
set.seed(1)
beta_gradNes <- (rnorm(dim(X)[2])) * 0.01
beta_gradNes1 <- NestrovGradientDescent(beta_gradNes, X, y)$beta
iteration.No3.1 <- NestrovGradientDescent(beta_gradNes, X, y)$iList
costList3.1 <- NestrovGradientDescent(beta_gradNes, X, y)$costList
precision_score(beta_gradNes1, X, y)
print(ConfusionMatrix(beta_gradNes1, X, y))

beta_gradNes2 <- NestrovGradientDescent(beta_gradNes, X, y, regulation = 2)$beta
iteration.No3.2 <- NestrovGradientDescent(beta_gradNes, X, y, regulation = 2)$iList
costList3.2 <- NestrovGradientDescent(beta_gradNes, X, y, regulation = 2)$costList
precision_score(beta_gradNes2, X, y)
print(ConfusionMatrix(beta_gradNes2, X, y))
```

```{r}
plot(c(1,50),c(50,500), type = "n", xlab = "Iteration.No", ylab = "CostFunc")
abline(h = seq(50,500, by = 20), v = 0:50, col = "lightgray", lty = 3)
lines(iteration.No1.1, costList1.1, col = "red1")
lines(iteration.No1.2, costList1.2, col = "red4")
lines(iteration.No2.1, costList2.1, col = "blue1")
lines(iteration.No2.1, costList2.1, col = "blue4")
lines(iteration.No3.1, costList3.1, col = "yellow1")
lines(iteration.No3.2, costList3.2, col = "yellow4")

legend("topright",                                    #图例位置为右上角
       legend=c("Gradient", "Gradient-L2", "Newton", "Newton-L2", "NestrovGradient", "NestrovGradient-L2"),        #图例内容
 col=c("red1","red4", "blue1", "blue4", "yellow1", "yellow4"),                 #图例颜色
lty=1,lwd=2)                                          #图例大小
```


